### PR TITLE
Fix GitHub license detection

### PR DESCRIPTION
**Pull request by shlomif**
So it will say GPL-2.0 and more people will want to take a look.

### CODE REVIEW

**Comment by thecharlieblake** [comment]
Hi Shlomi, happy to make this change - but can you tell me what the effect is? There is some automatic license detection which github isn't doing because of the filename copyright.txt? Where can one see the license detection?

**Comment by shlomif** [comment]
Hi @thecharlieblake ! 

> Hi Shlomi, happy to make this change - but can you tell me what the effect is? There is some automatic license detection which github isn't doing because of the filename copyright.txt? Where can one see the license detection?

See https://github.com/licensee/licensee (try the `--no-remote` flag). Basically, it allows GitHub/etc. to recognise the licence of the repo. See e.g https://github.com/search?utf8=%E2%9C%93&q=freecell%20solver where it says "MIT License" next to "fc-solve".

**Comment by thecharlieblake** [comment]
Ah I see - thanks for doing this. Hopefully will increase visibility!

**Comment by shlomif** [comment]
@thecharlieblake : hi! As a postscript to this pullreq see https://github.com/licensee/licensee/issues/466 . There is still some distance to go.

**Comment by thecharlieblake** [comment]
I saw that it didn't update when I merged but just assumed it would take some time for GitHub to update/crawl the repo. That may still be the case ofc. Will keep an eye on this, thanks!

**Comment by shlomif** [comment]
> I saw that it didn't update when I merged but just assumed it would take some time for GitHub to update/crawl the repo. That may still be the case ofc. Will keep an eye on this, thanks!

An update: the Licence has been detected now: https://github.com/thecharlieblake/Solvitaire ; it is still not displayed in this search however: https://github.com/search?utf8=%E2%9C%93&q=solvitaire .

**Comment by thecharlieblake** [comment]
That's good news! Hopefully it's just a timings issue then. Thanks for
letting me know.

Charlie

**Comment by thecharlieblake** [comment]
@shlomif success! https://github.com/search?utf8=%E2%9C%93&q=solvitaire now shows the license properly. Thanks for doing this.

**Comment by shlomif** [comment]
> @shlomif success! https://github.com/search?utf8=%E2%9C%93&q=solvitaire now shows the license properly. Thanks for doing this.

You're welcome! I received an email reply to my GitHub support ticket which said that it had been a reindexing problem and that they manually reindexed the Solvitaire's repository's record to fix it for us.

**Pull request merged**
